name: franka_valve
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.0.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.7.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.23.0
  - ca-certificates=2023.11.17
  - cachetools=5.3.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=1.6.0
  - cryptography=41.0.7
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-runtime=12.1.0
  - farama-notifications=0.0.4
  - ffmpeg=4.3.2
  - filelock=3.13.1
  - freetype=2.10.4
  - frozenlist=1.4.0
  - future=0.18.3
  - giflib=5.2.1
  - glfw=3.3.8
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - google-auth=2.25.2
  - google-auth-oauthlib=1.0.0
  - grpc-cpp=1.51.1
  - grpcio=1.51.1
  - gtest=1.14.0
  - gym=0.19.0
  - gymnasium=0.28.1
  - idna=3.6
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - intel-openmp=2022.1.0
  - jax-jumpy=1.0.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20230125.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libccd-double=2.1
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.8.1.2
  - libcurand=10.3.4.101
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgrpc=1.51.1
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libmujoco=2.3.5
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.25
  - libpng=1.6.37
  - libprotobuf=3.21.12
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lodepng=20220109
  - lz4-c=1.9.4
  - markdown=3.5.1
  - markupsafe=2.1.3
  - mkl=2022.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mujoco=2.3.5
  - mujoco-python=2.3.5
  - multidict=6.0.4
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.1
  - numpy=1.24.1
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openssl=3.2.0
  - pillow=9.4.0
  - pip=23.3.1
  - protobuf=4.21.12
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pybind11-abi=4
  - pycparser=2.21
  - pyglet=1.5.27
  - pyglfw=2.6.3
  - pyjwt=2.8.0
  - pyopengl=3.1.1a1
  - pyopenssl=23.3.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.18
  - python_abi=3.8
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - qhull=2020.2
  - re2=2023.02.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.8.1
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.12
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.0
  - tinyxml2=9.0.0
  - tk=8.6.12
  - torchaudio=2.1.1
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - urllib3=2.1.0
  - werkzeug=3.0.1
  - wheel=0.41.2
  - x264=1!161.3030
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.7
  - xorg-libxcursor=1.2.0
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.11
  - xorg-randrproto=1.5.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - astunparse==1.6.3
      - cycler==0.12.1
      - docutils==0.20.1
      - flatbuffers==24.3.25
      - fonttools==4.46.0
      - fsspec==2023.12.2
      - gast==0.4.0
      - google-pasta==0.2.0
      - h5py==3.11.0
      - importlib-resources==6.1.1
      - jaraco-classes==3.3.0
      - jeepney==0.8.0
      - keras==2.13.1
      - keyring==24.3.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown-it-py==3.0.0
      - matplotlib==3.7.4
      - mdurl==0.1.2
      - more-itertools==10.1.0
      - nh3==0.2.15
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.0.3
      - pkginfo==1.9.6
      - psutil==6.0.0
      - pybind11==2.11.1
      - pybind11-global==2.11.1
      - pygments==2.17.2
      - pytz==2023.3.post1
      - readme-renderer==42.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.7.0
      - sb3-contrib==1.4.0
      - secretstorage==3.3.3
      - stable-baselines3==1.4.0
      - tensorboardx==2.6.2.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - twine==4.0.2
      - typing-extensions==4.5.0
      - wrapt==1.16.0
